### ISSUE TITLE
Added scrollbarClassName prop to ActivityCalendar component for custom scrollbar styling

### ISSUE THREAD

**Issue by anudeep-17** [grubersjoe/react-activity-calendar#181]
> This enhancement is particularly useful when integrating `ActivityCalendar` into the `react-github-calendar` package. In scenarios where the calendar overflows horizontally (`overflow-x`) in a Next.js project, this new `scrollbarClassName` prop allows developers to apply custom scrollbar styles, ensuring a more cohesive and visually appealing design.

Added a new prop `scrollbarClassName` to the `ActivityCalendar` component to allow users to apply custom styles to the scrollbar of the calendar. This enhancement provides better customization options for the component's appearance.

### Changes Made
- Added `scrollbarClassName` prop to the `ActivityCalendar` component.
- Updated the `ActivityCalendar.stories.tsx` file to demonstrate the usage of the new prop.

### Benefits
- Allows for better customization of the scrollbar.
- Enhances the visual appearance of the calendar component.

### Example Usage
Here is an example of how to use the new `scrollbarClassName` prop:

```tsx
import './customScrollbar.css';

export const NarrowScreens: Story = {
  args: defaultProps,
  parameters: {
    docs: {
      source: {
        code: '<ActivityCalendar data={data} />',
      },
    },
  },
  render: args => {
    const data = useMemo(() => generateTestData({ maxLevel: args.maxLevel }), [args.maxLevel]);

    return (
      <div style={{ width: 480, maxWidth: '100%', border: 'dashed 1px #929292' }}>
        <ActivityCalendar {...args} data={data} scrollbarClassName="custom-scrollbar" />
      </div>
    );
  },
};
```

### Custom Scrollbar CSS
Here is an example of the custom scrollbar CSS:

```css
.custom-scrollbar {
  scrollbar-width: thin;
  scrollbar-color: #888 #f1f1f1;
}

.custom-scrollbar::-webkit-scrollbar {
  width: 8px;
}

.custom-scrollbar::-webkit-scrollbar-track {
  background: #f1f1f1;
}

.custom-scrollbar::-webkit-scrollbar-thumb {
  background-color: #888;
  border-radius: 10px;
  border: 2px solid #f1f1f1;
}

.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: #555;
}
```

### Related Files
- `ActivityCalendar.tsx`
- `ActivityCalendar.stories.tsx`

 
### Additional Information
Please let me know if there are any changes or improvements needed for this enhancement. I am happy to make any necessary updates.
